### ISSUE TITLE
ways to build the executable

### ISSUE THREAD

**Issue by tissatussa** [boettcherb/DeepBlunder-Chess-Engine#1]
i successfully compiled your latest source code although there's no Makefile or description : i just did `g++ *.cpp` in the concerning folder (i'm on Linux, i don't use the `.sln` file etc). You could supply a simple `g++` command to optimize the compilation ?

Btw. i had to add `#include <cstring>` on top of `Board.cpp` to prevent (only) one compile error :

```
Board.cpp: In member function ‘void Board::reset()’:
Board.cpp:111:10: error: ‘memcpy’ is not a member of ‘std’; did you mean ‘wmemcpy’?
  111 |     std::memcpy(pieces, defaultPieces, sizeof(defaultPieces));
      |          ^~~~~~
      |          wmemcpy
```

**Comment by boettcherb** [comment]
Thanks for writing this issue and reporting the error. Along with the newest release (v1.1.6), I created a Makefile in the src folder and added the missing header to Board.cpp. The makefile worked fine on my machine using WSL (Windows Subsystem for Linux), but let me know if it doesn't work for you on yours. Also, let me know if you find any more errors or have suggestions for features/improvements.
